### ISSUE TITLE
yarjuf doesn't work with rspec 3

### ISSUE THREAD

**Issue by chilicheech** [natritmeyer/yarjuf#10]
rspec 3 has a new formatter api and yarjuf doesn't work with it. Can we make changes to yarjuf to make it support rspec 3?

**Comment by bsnape** [comment]
Hi @chilicheech this is something I'm looking at for @natritmeyer when I get any spare time!

You might have to wait a little while longer as I've got a busy week and @natritmeyer is away for 2 weeks (so won't be able to merge in any fix yet).

**Comment by FredyKonig** [comment]
Hi Bsnape 
I saw in your fork that you deal with this issue. Is it working on your side?

**Comment by bsnape** [comment]
hey @FredyKonig I did start looking at this but I've been too busy with other work things in my evenings to finish it yet. I'm going to be away for a few days but I might be able to find some time on Sunday to progress things.

The `rspec-3-upgrade` branch in my fork is still a work in progress, apologies if anybody has tried to use it and got errors. You can see in my commits that I've tried to adhere to the RSpec 2 formatter API (using the new `rspec-legacy-formatters` gem) but I've also experimented (locally on my machine) to switch to the new RSpec 3 formatter API instead, which is probably the best long-term option.

It seems that the way that yarjuf was retrieving RSpec metadata about the tests you run has been deprecated so it isn't a trivial fix (as far as I can tell).

**Comment by bsnape** [comment]
I managed to find some free time last night to work on this. The fix is almost complete (hopefully will finish it tonight).

**Comment by natritmeyer** [comment]
Closed by #13
