### ISSUE TITLE
Missing 'builder' dependency

### ISSUE THREAD

**Issue by broquaint** [natritmeyer/yarjuf#2]
Looks like yarjuf depends on 'builder' but doesn't declare it in the Gemfile.

Cheers,
Dan / broquaint

**Comment by natritmeyer** [comment]
WHAT!? I thought builder was part of core ruby. I'll fix that tonight. Thanks!

**Comment by natritmeyer** [comment]
Just released v1.0.2 - builder dependency added!

**Comment by broquaint** [comment]
Nice one! :+1:
