### ISSUE TITLE
rspec-core 2.12.1 format_backtrace unbroken

### ISSUE THREAD

**Issue by jeedo** [natritmeyer/yarjuf#3]
In the latest version of rspec_core the format_backtrace was "fixed" by adding in 2 arguments: https://github.com/rspec/rspec-core/commit/f06254c00770387e3a8a2efbdbc973035c217f6a

So now running the the formatter results in a Argument Error:

```
d:/Ruby193/lib/ruby/gems/1.9.1/gems/rspec-core-2.12.1/lib/rspec/core/formatters/
base_formatter.rb:124:in `format_backtrace': wrong number of arguments (1 for 2) (ArgumentError)
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/yarjuf-1.0.2/lib/yarjuf.rb:45:in `failure_details_for'
        from d:/Ruby193/lib/ruby/gems/1.9.1/gems/yarjuf-1.0.2/lib/yarjuf.rb:69:in `block (6 levels) in dump_summary'
```

**Comment by natritmeyer** [comment]
Thanks for pointing that out - I've reverted yarjuf now that https://github.com/rspec/rspec-core/commit/f06254c00770387e3a8a2efbdbc973035c217f6a is fixed!

New version: 1.0.3
