### ISSUE TITLE
Jenkins not generating test image

### ISSUE THREAD

**Issue by phlegx** [natritmeyer/yarjuf#4]
Hi,

I followed your HOWTO regarding jaryuf and Jenkins. The XML file is generated  and there are values. However jenkins shows me "no tests" on the dashboard:

![no_tests](https://f.cloud.github.com/assets/111506/83008/7524cdbe-63c9-11e2-8d70-72723b19b591.png)

but when I go into the link then the Tests are there. Now unfortunately my Graph remains empty:

![test_result_trend](https://f.cloud.github.com/assets/111506/83010/8fe7f27a-63c9-11e2-8682-050e6d8245e6.png)

Do you have any ideas what could be wrong?

thank you
p

**Comment by natritmeyer** [comment]
It _looks_ like Jenkins is looking in the wrong place for the `results.xml` file (or whatever you've called the output file)...

Also, what version of Jenkins are you running?

**Comment by phlegx** [comment]
It's Jenkins version 1.478

When I click on the "Latest Test results" (first pic in my first post) the tests are shown to me, even though next to it it says "no tests" Looks like for every Build the tests have indeed be recorded and "archived". But yeah, the graph is still empty. Maybe a Jenkins bug?

Here is the setup for the result.xml file. The file is indeed generated into that folder:

![jenkins_test_results](https://f.cloud.github.com/assets/111506/86208/495c6400-648f-11e2-99ab-edd2f8bf622c.png)

thank you
p

**Comment by natritmeyer** [comment]
It could be a bug in Jenkins, but it could also be a bug in yarjuf. If so, this is the first I've heard of it. Is there an exception in a jenkins log somewhere? Is `results.xml` coming out as valid xml?

**Comment by phlegx** [comment]
I tested the file with 'xmllint'

<pre>
xmllint --valid --noout results.xml
results.xml:2: validity error : Validation failed: no DTD found !
ipped="12" tests="76" time="122.479098532" timestamp="2013-01-22T17:33:31+01:00"
</pre>

Not sure if this might be the cause?
First part of the results.xml file where the error occurs:

https://gist.github.com/4603259

thank you
p

**Comment by natritmeyer** [comment]
No, that's expected. And the contents of the gist looks fine, too. Curiouser and curiouser...

**Comment by phlegx** [comment]
Do I have to "aggregate" the test results so the graph is showing to me?

If yes what are the settings to do that with yarjuf?

**Comment by natritmeyer** [comment]
What do you mean by "aggregate"?

**Comment by phlegx** [comment]
Like set an additional option somewhere that combines all test results of all builds. But I guess that is not the problem though.

I will update Jenkins soon and let you know then if the problem disappeared.

thank you
p

**Comment by natritmeyer** [comment]
Assuming this problem has disappeared - haven't heard for ~3 months...

**Comment by phlegx** [comment]
Hi

the problems still persists but I didn't looked into it anymore. Just a quick update: I updated jenkins several times now, but it didn't change unfortunately.
