### ISSUE TITLE
Color output can cause Jenkins failure if a test generates a diff.

### ISSUE THREAD

**Issue by hivehand** [natritmeyer/yarjuf#7]
(Apologies in advance if I’m overlooking the blindingly obvious, as I am a relatively new yarjuf user.)

We have a Jenkins job configured to generate color output, with Jenkins parsing the ANSI color escape sequences. This makes it very easy to spot errors (red) amidst the successes (green) when skimming the log, and up ’til now yarjuf has had no issue with that.

However, it turns out that if a failing test case happens to generate a diff, then that diff is also colorized. In the log, that’s fine and welcome. However, yarjuf appears to incorporate the unmodified output, complete with color-generating escape sequences, into the XML, causing JUnit processing to reject results.xml “An invalid XML character (Unicode: 0x1b) was found in the CDATA section.”

The expedient thing is to simply strip out the escape sequences, using sed, after rspec has finished its work, with a command like this:

``` bash
sed -r -e "s/\x1B\[[0-9]+m//g" -i results.xml
```

But it would be nice if yarjuf knew to do the equivalent right out of the box.

Versions in use:

Jenkins: 1.509
rspec: 2.13.0

Please let me know if any additional information would be helpful — or if I’m going about things in a fundamentally-wrong way.

**Comment by natritmeyer** [comment]
Yeah, so on that "fundamentally wrong" thing... :)

You shouldn't be piping colored output into Jenkins for exactly the reason you give - it's not expecting it and doesn't know how to handle it.
